version: '3.8'

services:
  env:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../workspace:/workspace:cached
      - ../environment/cache/m2:/root/.m2
      - /var/run/docker.sock:/var/run/docker.sock 
    command: sleep infinity

  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres  
    network_mode: service:env
    restart: unless-stopped  
    volumes:
      - ../environment/volumes/postgresql:/var/lib/postgresql/data

    # As in the "app" service, use "forwardPorts" in **devcontainer.json** to forward an app port locally.